### ISSUE TITLE
Cephなどを使用せず、hostpathを有効化して、ストレージクラスを使える様にする方法

### ISSUE THREAD

**Issue by takara9** [takara9/marmot-servers#1]
## 準備

kube-controller-manager の起動パラメータに `--enable-hostpath-provisioner=true` を追加する

```
root@master1:/home/ubuntu# cd /etc/kubernetes/manifests/
root@master1:/etc/kubernetes/manifests# ls
etcd.yaml            kube-controller-manager.yaml
kube-apiserver.yaml  kube-scheduler.yaml

root@master1:/etc/kubernetes/manifests# cat -n  kube-controller-manager.yaml |grep enable-hostpath-provisioner
    24	    - --enable-hostpath-provisioner=true
```

## 使用法

プロビジョナー kubernetes.io/host-path で、ストレージクラスを作成する

```
cat <<EOF | kubectl create -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: standard
provisioner: kubernetes.io/host-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
EOF
```

```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic-test
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1G
  accessModes:
  - ReadWriteOnce
EOF

kubectl get pv
```

ポッドからマウント

```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: my-linux
      image: ubuntu:latest
      command: ["/usr/bin/sleep"]
      args: ["1800"]  
      volumeMounts:
      - name: pv-data 
        mountPath: /mnt
  volumes:
    - name: pv-data
      persistentVolumeClaim:  
        claimName:  pvc-dynamic-test
EOF
```
